---
title: "CV/Resume"

---

## Experience


**Upward Bound Mentor and Natural Science Tutor** - **2018 – 2019** (Summer Position)  
Oxnard College, Oxnard, CA 93033  

* Mentored a group of 6 students through a 6-week college course at Oxnard college
*  Coordinated and facilitated recreational activities to build community among group during mentor hour  
* Attended general chemistry and biology class to assist professor and students with lab experiments and reports  
* Helped students complete their homework assignments  
* Prepared students for weekly quizzes by testing them on course material
* Chaperoned students during field trips to university campuses  
* Responsible for taking photos and posting them to social media accounts such as Instagram and Twitter  

**Recreation Leader I/Project Coordinator** - **2017 – 2018** 
City of Oxnard, Oxnard, CA 93033  

*  Responsible for the coordination of the city’s Green Business Certification Program  
* Developed a marketing plan to increase visibility and registration of the Green Business Certification Program  
* Visited businesses to talk about the Green Business Certification Program and encourage enrollment  
* Assisted businesses with certification process: registration, completion of checklists, and implementation of green practices  
* Facilitated onsite inspections to verify implementation of green practices 
* Helped supervisor with grant progress reports and data entry  
* Supported other city departments and divisions with municipal projects and events such as: Public Works, Animal safety, Engineering and Design, and Recreation and Community Services  

**Assessment, Outreach and Recruitment Student Specialist** - **2016 – 2018**  
Oxnard College, Oxnard, CA 93033  

* Proctored assessment exams  
* Explained exam results to students
* Entered exam scores into data base system  
* Maintained cleanliness of assessment lab  
* Attended community outreach events to promote Oxnard College  
* Co-facilitated workshops and presentations on admission processes and Oxnard College  

**Foreclosure Prevention Counselor** - **2014 – 2016** 
Ventura County Community Development Corporation,  Oxnard, CA 93030  

* Counseled homeowners at risk of losing their homes to foreclosure  
* Analyzed circumstances and presented homeowners with solutions  
* Created detailed action plans to meet homeowners’ goals  
* Assisted homeowners with application process for state and federal home preservation assistance programs  
* Communicated with mortgage servicers and program staff for follow-up purposes on behalf of the homeowners  
* Conducted workshops and presentations on various topics such as: foreclosure prevention and financial literacy  


## Education 
Bachelor of Arts, Geography, GIS Emphasis - **2018 - 2021**  
Minor: Education Studies  
University of California, Santa Barbara 

Associate of Arts, Geography - **2014 - 2018**  
Oxnard College