
navbar:
  title: "Meaningful Maps"
  left:
    - text: "Home"
      href: index.html
      icon: fa-home
    - text: "GIS Work"
      href: geog176A.html
      icon: fa-globe
  right:
    - icon: fa-github
      href: https://github.com/albertdominguez1/geog176A_2020
output:
  html_document:
    theme: flatly 
